apiVersion: test.autumn.io/v1
kind: ElasticWeb
metadata:
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/instance: elasticweb-sample
    app.kubernetes.io/part-of: elasticweb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: elasticweb
  name: elasticweb-sample
spec:
    name: elastic-web
    image: tomcat:8.0.18-jre8
    port: 30003
    singlePodQPS: 100
    totalQPS: 1001
