# permissions for end users to edit elasticwebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: elasticweb-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: elasticweb
    app.kubernetes.io/part-of: elasticweb
    app.kubernetes.io/managed-by: kustomize
  name: elasticweb-editor-role
rules:
- apiGroups:
  - test.autumn.io
  resources:
  - elasticwebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.autumn.io
  resources:
  - elasticwebs/status
  verbs:
  - get
