# permissions for end users to view guestbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: guestbook-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helloworld
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-viewer-role
rules:
- apiGroups:
  - webapp.autumn.io
  resources:
  - guestbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.autumn.io
  resources:
  - guestbooks/status
  verbs:
  - get
